INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106178, 'Afghanistan' , 'AF', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98371, 'Albania' , 'AL', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (108361, 'Algeria' , 'DZ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105240, 'Angola' , 'AO', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105297, 'Argentina' , 'AR', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104951, 'Armenia' , 'AM', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99031, 'Australia' , 'AU', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (112827, 'Austria' , 'AT', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105381, 'Azerbaijan' , 'AZ', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (496739, 'Bahamas' , 'BS', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (124206, 'Bahrain' , 'BH', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98368, 'Bangladesh' , 'BD', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105581, 'Belarus' , 'BY', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98727, 'Belgium' , 'BE', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (360425, 'Belize' , 'BZ', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (108400, 'Benin' , 'BJ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (266192, 'Bhutan' , 'BT', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (123515, 'Bosnia and Herzegovina' , 'BA', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104213, 'Botswana' , 'BW', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98873, 'Brazil' , 'BR', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (103748, 'Bulgaria' , 'BG', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (288513, 'Burkina Faso' , 'BF', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (279662, 'Burundi' , 'BI', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98611, 'Cambodia' , 'KH', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104344, 'Cameroon' , 'CM', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98473, 'Canada' , 'CA', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (333678, 'Cape Verde' , 'CV', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (284576, 'Chad' , 'TD', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (107598, 'Chile' , 'CL', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98789, 'China' , 'CN', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (113293, 'Colombia' , 'CO', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (111139, 'Costa Rica' , 'CR', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (113171, 'Croatia' , 'HR', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (117385, 'Cyprus' , 'CY', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98502, 'Denmark' , 'DK', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (292417, 'Dominica' , 'DM', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104885, 'Dominican Republic' , 'DO', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (335761, 'Ecuador' , 'EC', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98838, 'Egypt' , 'EG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (205832, 'Equatorial Guinea' , 'GQ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104963, 'Estonia' , 'EE', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98703, 'Ethiopia' , 'ET', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (108902, 'Fiji' , 'FJ', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99533, 'Finland' , 'FI', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98460, 'France' , 'FR', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98675, 'Gambia' , 'GM', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106627, 'Georgia' , 'GE', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98391, 'Germany' , 'DE', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98411, 'Ghana' , 'GH', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98577, 'Greece' , 'GR', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105873, 'Grenada' , 'GD', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (302286, 'Guadeloupe' , 'GP', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (112632, 'Guatemala' , 'GT', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (279419, 'Guinea' , 'GN', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98470, 'Honduras' , 'HN', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104022, 'Hong Kong' , 'HK', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104141, 'Hungary' , 'HU', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106637, 'Iceland' , 'IS', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98396, 'India' , 'IN', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98520, 'Indonesia' , 'ID', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (110741, 'Iraq' , 'IQ', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98442, 'Ireland' , 'IE', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98517, 'Israel' , 'IL', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99437, 'Italy' , 'IT', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98729, 'Jamaica' , 'JM', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98489, 'Japan' , 'JP', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (116738, 'Kazakhstan' , 'KZ', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98508, 'Kenya' , 'KE', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98423, 'Kuwait' , 'KW', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (116934, 'Kyrgyzstan' , 'KG', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104859, 'Latvia' , 'LV', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98722, 'Lebanon' , 'LB', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (250842, 'Lesotho' , 'LS', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106442, 'Liberia' , 'LR', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104745, 'Luxembourg' , 'LU', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98477, 'Macao' , 'MO', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (122690, 'Madagascar' , 'MG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98506, 'Malawi' , 'MW', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98672, 'Malaysia' , 'MY', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105101, 'Maldives' , 'MV', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (112829, 'Mali' , 'ML', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104662, 'Malta' , 'MT', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (280003, 'Martinique' , 'MQ', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (120341, 'Mauritania' , 'MR', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98841, 'Mauritius' , 'MU', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98528, 'Mexico' , 'MX', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (278034, 'Mongolia' , 'MN', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (287517, 'Montenegro' , 'ME', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99711, 'Morocco' , 'MA', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (109042, 'Mozambique' , 'MZ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104755, 'Namibia' , 'NA', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106272, 'Nepal' , 'NP', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98362, 'Netherlands' , 'NL', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (524597, 'New Caledonia' , 'NC', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99416, 'New Zealand' , 'NZ', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (563677, 'Niger' , 'NE', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98440, 'Nigeria' , 'NG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104935, 'Norway' , 'NO', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98782, 'Oman' , 'OM', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98732, 'Pakistan' , 'PK', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (107658, 'Panama' , 'PA', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99281, 'Papua New Guinea' , 'PG', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (109072, 'Paraguay' , 'PY', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98416, 'Peru' , 'PE', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98363, 'Philippines' , 'PH', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98582, 'Poland' , 'PL', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104276, 'Portugal' , 'PT', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (273906, 'Puerto Rico' , 'PR', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104495, 'Qatar' , 'QA', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98826, 'Romania' , 'RO', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104107, 'Rwanda' , 'RW', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106283, 'Saint Lucia' , 'LC', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98424, 'Saudi Arabia' , 'SA', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (233308, 'Senegal' , 'SN', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98844, 'Serbia' , 'RS', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98610, 'Seychelles' , 'SC', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98430, 'Sierra Leone' , 'SL', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98466, 'Singapore' , 'SG', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98529, 'Slovenia' , 'SI', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99358, 'Somalia' , 'SO', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98514, 'South Africa' , 'ZA', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104865, 'Spain' , 'ES', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98636, 'Sri Lanka' , 'LK', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98504, 'Sudan' , 'SD', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (275441, 'Swaziland' , 'SZ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98975, 'Sweden' , 'SE', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (105519, 'Switzerland' , 'CH', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98532, 'Taiwan' , 'TW', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98492, 'Thailand' , 'TH', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98864, 'Togo' , 'TG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (117675, 'Tonga' , 'TO', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (109902, 'Trinidad and Tobago' , 'TT', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98381, 'Tunisia' , 'TN', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98677, 'Turkey' , 'TR', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (119977, 'Turkmenistan' , 'TM', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98662, 'Uganda' , 'UG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98749, 'Ukraine' , 'UA', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98966, 'United Arab Emirates' , 'AE', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98472, 'United Kingdom' , 'GB', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98361, 'United States' , 'US', 'North America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99290, 'Uzbekistan' , 'UZ', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99763, 'Vanuatu' , 'VU', 'Oceania' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (427144, 'Yemen' , 'YE', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98435, 'Zambia' , 'ZM', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98764, 'Zimbabwe' , 'ZW', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (108430, 'Bolivia' , 'BO', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (99733, 'Czechia' , 'CZ', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (480751, 'East Timor' , 'TL', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98438, 'Hashemite Kingdom of Jordan' , 'JO', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98417, 'Iran' , 'IR', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98619, 'Ivory Coast' , 'CI', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (104798, 'Laos' , 'LA', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98557, 'Libya' , 'LY', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (122263, 'Macedonia' , 'MK', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98367, 'Myanmar [Burma]' , 'MM', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98852, 'Palestine' , 'PS', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (118587, 'Réunion' , 'RE', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98810, 'Republic of Korea' , 'KR', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106113, 'Republic of Lithuania' , 'LT', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (103676, 'Republic of Moldova' , 'MD', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (106334, 'Republic of the Congo' , 'CG', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98388, 'Russia' , 'RU', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98756, 'Slovak Republic' , 'SK', 'Europe' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (117921, 'Syria' , 'SY', 'Asia' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (98649, 'Tanzania' , 'TZ', 'Africa' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (123916, 'Venezuela' , 'VE', 'South America' );  
INSERT INTO pays  (pays_id, libelle, code_pays, continent) VALUES (122714, 'Vietnam' , 'VN', 'Asia' );  